// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Program.cs" company="Proligence">
//   Copyright (c) 2011 Proligence, All Rights Reserved.
// </copyright>
// <auto-generated />
// --------------------------------------------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ps", Scope = "namespace", Target = "Orchard.Management.PsProvider.Agents")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ps", Scope = "namespace", Target = "Orchard.Management.PsProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ps", Scope = "namespace", Target = "Orchard.Management.PsProvider.Agents")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ps", Scope = "namespace", Target = "Orchard.Management.PsProvider.Host")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ps", Scope = "namespace", Target = "Orchard.Management.PsProvider.Host")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ps")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ps")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Orchard.Management.PsProvider.OrchardProviderContainer.#GetContainer()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ps", Scope = "type", Target = "Orchard.Management.PsProvider.OrchardPsSnapIn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ps", Scope = "type", Target = "Orchard.Management.PsProvider.OrchardPsSnapIn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "AgentAttribute", Scope = "member", Target = "Orchard.Management.PsProvider.Agents.AgentProxy.#.ctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope = "member", Target = "Orchard.Management.PsProvider.Host.OrchardHostContextProvider.#CreateAgent`1()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope = "member", Target = "Orchard.Management.PsProvider.Host.OrchardHostContextProvider.#CreateOrchardHost(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ps", Scope = "namespace", Target = "Orchard.Management.PsProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ps", Scope = "namespace", Target = "Orchard.Management.PsProvider.Cmdlets")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ps", Scope = "namespace", Target = "Orchard.Management.PsProvider.Cmdlets")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ps", Scope = "type", Target = "Orchard.Management.PsProvider.Cmdlets.GetOrchardPsCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ps", Scope = "type", Target = "Orchard.Management.PsProvider.Cmdlets.GetOrchardPsCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Get-OrchardPsCommand", Scope = "member", Target = "Orchard.Management.PsProvider.OrchardProvider.#InitializeOrchardDrive(System.Management.Automation.PSDriveInfo,Orchard.Management.PsProvider.OrchardDriveParameters)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "CommandName", Scope = "member", Target = "Orchard.Management.PsProvider.OrchardProvider.#InitializeOrchardDrive(System.Management.Automation.PSDriveInfo,Orchard.Management.PsProvider.OrchardDriveParameters)")]
